apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hanzo

resources:
  - ../base
  - ingress.yaml

configMapGenerator:
  - name: status-config
    files:
      - config.yaml=../../config/hanzo.yaml

generatorOptions:
  disableNameSuffixHash: true
