web:
  port: 8080

storage:
  type: sqlite
  path: /data/status.db

ui:
  title: "Ad Nexus Status"
  description: "Real-time service health and performance"
  header: "Status"
  logo: "/brands/nexus/logo.svg"
  link: "https://ad.nexus"
  favicon:
    default: "/brands/nexus/favicon-32.png"
    size16x16: "/brands/nexus/favicon-16.png"
    size32x32: "/brands/nexus/favicon-32.png"
  buttons:
    - name: "Ad Nexus"
      link: "https://ad.nexus"

endpoints:

  # ===============================================
  # CORE
  # ===============================================

  - name: "Website"
    group: "Core"
    url: "https://ad.nexus"
    interval: 60s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 3000"
      - "[CERTIFICATE_EXPIRATION] > 720h"
