web:
  port: 8080

storage:
  type: sqlite
  path: /data/status.db

ui:
  title: "Pars Status"
  description: "Real-time network health and performance"
  header: "Status"
  logo: "/brands/pars/logo.svg"
  link: "https://pars.network"
  favicon:
    default: "/brands/pars/favicon.svg"
    size16x16: "/brands/pars/favicon-16.png"
    size32x32: "/brands/pars/favicon-32.png"
  dark-mode: true
  buttons:
    - name: "Docs"
      link: "https://docs.pars.network"
    - name: "GitHub"
      link: "https://github.com/parsnet"
    - name: "Support"
      link: "https://pars.network/support"

endpoints:

  # ===============================================
  # CORE
  # ===============================================

  - name: "Website"
    group: "Core"
    url: "https://pars.network"
    interval: 60s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 3000"
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: "Identity"
    group: "Core"
    url: "https://pars.id"
    interval: 60s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 720h"
