web:
  port: 8080

storage:
  type: sqlite
  path: /data/status.db

ui:
  title: "Zoo Status"
  description: "Real-time research infrastructure health"
  header: "Status"
  logo: "/brands/zoo/logo.svg"
  link: "https://zoo.ngo"
  favicon:
    default: "/brands/zoo/favicon.svg"
    size16x16: "/brands/zoo/favicon-16.png"
    size32x32: "/brands/zoo/favicon-32.png"
  dark-mode: true
  buttons:
    - name: "ZIPs"
      link: "https://zips.zoo.ngo"
    - name: "GitHub"
      link: "https://github.com/zoolabs"
    - name: "Support"
      link: "https://zoo.ngo/support"

endpoints:

  # ===============================================
  # CORE
  # ===============================================

  - name: "Website"
    group: "Core"
    url: "https://zoo.ngo"
    interval: 60s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 3000"
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: "ZIPs"
    group: "Core"
    url: "https://zips.zoo.ngo"
    interval: 60s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 3000"
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: "Identity"
    group: "Core"
    url: "https://zoo.id"
    interval: 60s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 720h"
