apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lux-system

resources:
  - namespace.yaml
  - ../base
  - ingress.yaml

configMapGenerator:
  - name: status-config
    files:
      - config.yaml=../../config/lux.yaml

generatorOptions:
  disableNameSuffixHash: true
